# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and Test DefaultsKit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 16.0
        run: sudo xcode-select -s /Applications/Xcode.app/

      - name: Build Package
        run: swift build

      - name: Run Tests
        run: swift test
